// day.js — the Daily Readings page (#/day/YYYY-MM-DD and #/day/today).
// Renders the day's synaxarion entry (title/feast, saints, and a link into
// the library's own "Lives" item when one exists) and the appointed
// readings, each annotated with the St John Chrysostom homily that covers
// it — computed from data/lectionary/chrysostom-map.json (the homily whose
// start is the LAST start <= the reading's start, [chapter, verse]
// lexicographic; start=null entries are introductions and never match).
// The homily links internally to #/item/<id> when data/index.json has an
// item with the matching source_ref ("Homily 56 on Matthew"), else out to
// the public-domain translation on New Advent. Books with no series in the
// map (Mark, Luke, 2 Peter, …) get a plain note — Chrysostom left no
// homily series on them.
//
// Data contract (fixture now, generated full datasets later, same shape):
//   data/lectionary/days/<YYYY>.json — {year, pascha, days:{"YYYY-MM-DD":
//     {titles[], feast_level, fast|null, saints[], readings:[{label, ref,
//     book, from:[c,v], to:[c,v]}]}}}
//   data/lectionary/chrysostom-map.json — {Book: {series, newadvent_base,
//     homilies:[{n, start:[c,v]|null}]}}
//   data/reading-icons.json — {books: {book code: image path}, ot_books:
//     {OT book name: image path}} — the icon beside a reading; a reading
//     with no match renders text-only, with no empty frame.
//   data/lectionary/reading-texts/<date>.json — {date, readings:[{ref,
//     heading, verses[]}]} — generated by scripts/build_reading_texts.py from
//     content/<date>/readings.md's "Easy English" sections, primary readings
//     only. Matched to a day's reading objects by exact `ref` string (dashes
//     normalized); a day with no file, or a reading with no matching ref,
//     renders no disclosure at all.
// Year files load lazily and are cached in memory for the page's lifetime;
// a missing year file or date key renders the graceful "not available"
// state, never a console error.
//
// Rendering: a full-width hero band carries the day's own mosaic cover
// (from data/covers.json via the synaxarion item's cover_key, the same
// lookup js/browse.js does for its row thumbnails), the prev/next arrows,
// the date heading, the feast title(s) and the fast rule. Below it the
// body is one typographic flow — no cards: a quiet "Commemorated:" line,
// an inline "Read the Lives" link, then the primary readings ("At the
// Liturgy" — the large serif reference is the anchor of each entry, with
// its Chrysostom homily note underneath), and only on major feasts a
// quieter "Also Appointed" list of the Vespers/Matins lections. Styles in
// css/day.css.
import { ROOT } from './paths.js';
import { loadIndex } from './catalogue.js';
import { ICON_BOOK_CROSS, ICON_SAINT, ICON_FISH, ICON_CHEVRON_RIGHT, ICON_SCROLL } from './day-icons.js';

const GOSPEL_BOOKS = ['Matt', 'Mark', 'Luke', 'John'];
const NT_BOOKS = new Set(['Matt', 'Mark', 'Luke', 'John', 'Acts', 'Rom', '1Cor', '2Cor', 'Gal', 'Eph', 'Php', 'Col', '1Th', '2Th', '1Tim', '2Tim', 'Titus', 'Phlm', 'Heb', 'Jas', '1Pet', '2Pet', '1Jn', '2Jn', '3Jn', 'Jude', 'Rev']);

let mapPromise = null;
let coversPromise = null;
let readingIconsPromise = null;
const yearPromises = new Map();

function loadChrysostomMap() {
  if (!mapPromise) {
    mapPromise = fetch(`${ROOT}data/lectionary/chrysostom-map.json`)
      .then((res) => (res.ok ? res.json() : {}))
      .catch(() => ({}));
  }
  return mapPromise;
}

// cover_key -> {image, medallion, focus}; used by the hero band.
// Cached for the page's lifetime like the map.
function loadCovers() {
  if (!coversPromise) {
    coversPromise = fetch(`${ROOT}data/covers.json`)
      .then((res) => (res.ok ? res.json() : {}))
      .catch(() => ({}));
  }
  return coversPromise;
}

// book code / OT book name -> icon image path, for the arched plates and
// thumbs beside each reading. Generated from the manifest's
// reading_icon_map by scripts/build_data.py. Cached for the page's
// lifetime like the covers; a missing file means no icons, not an error.
function loadReadingIcons() {
  if (!readingIconsPromise) {
    readingIconsPromise = fetch(`${ROOT}data/reading-icons.json`)
      .then((res) => (res.ok ? res.json() : {}))
      .catch(() => ({}));
  }
  return readingIconsPromise;
}

// date -> {date, readings:[{ref, heading, verses[]}]} | null. One singleton
// promise per date (unlike the map/covers/icons caches above, which are
// global for the page's lifetime) — generated by scripts/build_reading_texts.py;
// a day with no file is the common case, not an error.
const readingTextPromises = new Map();
function loadReadingText(dateStr) {
  if (!readingTextPromises.has(dateStr)) {
    readingTextPromises.set(
      dateStr,
      fetch(`${ROOT}data/lectionary/reading-texts/${dateStr}.json`)
        .then((res) => (res.ok ? res.json() : null))
        .catch(() => null)
    );
  }
  return readingTextPromises.get(dateStr);
}

// Returns the parsed year file, or null when the file is absent / the fetch
// failed — callers treat null as "no data for this year", not as an error.
// Exported for the calendar browser (js/tree.js), which renders the same
// year files as month/day grids.
export function loadYear(year) {
  if (!yearPromises.has(year)) {
    yearPromises.set(
      year,
      fetch(`${ROOT}data/lectionary/days/${year}.json`)
        .then((res) => (res.ok ? res.json() : null))
        .catch(() => null)
    );
  }
  return yearPromises.get(year);
}

export async function loadDay(dateStr) {
  const year = dateStr.slice(0, 4);
  const data = await loadYear(year);
  return data && data.days ? data.days[dateStr] || null : null;
}

function pad2(n) {
  return String(n).padStart(2, '0');
}

// Local (not UTC) date string — "#/day/today" must mean the reader's own day.
function localDateStr(d) {
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
}

function shiftDate(dateStr, days) {
  const [y, m, d] = dateStr.split('-').map(Number);
  const dt = new Date(y, m - 1, d + days);
  return localDateStr(dt);
}

function formatDateHeading(dateStr) {
  const [y, m, d] = dateStr.split('-').map(Number);
  return new Date(y, m - 1, d).toLocaleDateString('en-US', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

function cmp(a, b) {
  return a[0] - b[0] || a[1] - b[1];
}

// Every homily whose stretch of the book overlaps the reading. A homily's
// stretch runs from its own start to just before the NEXT homily's start —
// so a pericope that straddles a boundary (1 Cor 4:9-16 begins in Homily
// 12's verses but its heart is Homily 13's) lists both, the way the
// library's own Sunday packages pair them. Introductions (start: null)
// never match.
function findHomilies(bookEntry, from, to) {
  const hs = (bookEntry.homilies || []).filter((h) => h.start);
  const found = [];
  hs.forEach((h, i) => {
    const next = i + 1 < hs.length ? hs[i + 1].start : null;
    const overlaps = cmp(h.start, to || from) <= 0 && (!next || cmp(next, from) > 0);
    if (overlaps) found.push(h);
  });
  return found;
}

// "Homilies on Matthew" -> "Matthew"; "Commentary on Galatians" -> "Galatians"
// — the book's name as it appears in a source_ref like "Homily 56 on Matthew".
function seriesBookName(series) {
  return String(series).replace(/^(?:Homilies|Commentary) on /, '');
}

function el(tag, className, html) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (html !== undefined) node.innerHTML = html;
  return node;
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

function text(tag, className, value) {
  const node = el(tag, className);
  node.textContent = value;
  return node;
}

const CHEVRON_LEFT =
  '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="14,6 8,12 14,18"/></svg>';
const CHEVRON_RIGHT =
  '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="10,6 16,12 10,18"/></svg>';
const EXTERNAL_SVG =
  '<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 4h6v6"/><path d="M20 4L10 14"/><path d="M19 13v6a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 3 19V6.5A1.5 1.5 0 0 1 4.5 5H11"/></svg>';

// The line under a reading: the Chrysostom homily covering it, linked into
// the library when we hold the text, out to New Advent when we don't, or a
// plain note when no series exists for the book at all.
function buildHomilyNote(reading, map, itemsBySourceRef, itemsByHomilyKey) {
  // Old Testament readings (Vespers, the Hours) carry no book code and get
  // no homily note at all — the note belongs to the NT pericopes only.
  if (!reading.book || !NT_BOOKS.has(reading.book)) return null;

  const note = el('p', 'day-homily');
  const bookEntry = map[reading.book];

  if (!bookEntry) {
    const what = GOSPEL_BOOKS.includes(reading.book) ? 'on this evangelist' : 'on this book';
    note.appendChild(text('span', 'day-homily-none', `St John Chrysostom left no homily series ${what}.`));
    return note;
  }

  let homilies = findHomilies(bookEntry, reading.from, reading.to);
  if (!homilies.length) {
    note.appendChild(text('span', 'day-homily-none', 'No Chrysostom homily on record covers this passage.'));
    return note;
  }
  // Very long composites (the Passion Gospels) can span many homilies —
  // keep the page readable.
  let overflow = 0;
  if (homilies.length > 4) {
    overflow = homilies.length - 3;
    homilies = homilies.slice(0, 3);
  }

  const bookName = seriesBookName(bookEntry.series);
  const inLibrary = (h) =>
    itemsBySourceRef.get(`Homily ${h.n} on ${bookName}`) ||
    itemsByHomilyKey.get(`${reading.book}:${h.n}`);

  homilies.forEach((homily, i) => {
    const label = i === 0
      ? `St John Chrysostom, Homily ${homily.n} on ${bookName}`
      : `Homily ${homily.n}`;
    const item = inLibrary(homily);
    if (i > 0) note.appendChild(text('span', 'day-homily-sep', ' · '));

    if (item) {
      const a = el('a', 'day-homily-link');
      a.href = `#/item/${item.id}`;
      a.textContent = label;
      note.appendChild(a);
    } else {
      const a = el('a', 'day-homily-link day-homily-external');
      a.href = `https://www.newadvent.org/fathers/${bookEntry.newadvent_base}${pad2(homily.n)}.htm`;
      a.target = '_blank';
      a.rel = 'noopener';
      a.appendChild(document.createTextNode(label + ' '));
      a.insertAdjacentHTML('beforeend', EXTERNAL_SVG);
      note.appendChild(a);
    }
  });
  if (overflow) {
    note.appendChild(text('span', 'day-homily-src', ` — and ${overflow} more in this series`));
  }
  if (homilies.some((h) => !inLibrary(h))) {
    note.appendChild(text('span', 'day-homily-src', ' — public-domain translation at New Advent'));
  }
  return note;
}

// A quiet "nothing here" note: icon + faint text, used for every graceful
// empty state (bad date, missing year file, missing readings, no Lives).
function emptyNote(icon, message) {
  const p = el('p', 'day-empty-note', icon);
  p.appendChild(text('span', null, message));
  return p;
}

// The small on-image chip beside the hero's date/title cluster: the day's
// own medallion (already curated, the same image buildCommemoration shows
// next to "Commemorated:") when its cover has one, else the abstract
// ICON_SAINT line icon — never an AI-generated or guessed face. Shown on
// every valid day, cover or no cover.
function buildSaintChip(cover) {
  if (cover && cover.medallion) {
    const chip = el('div', 'day-hero-saint');
    const img = el('img', 'day-hero-saint-img');
    img.src = ROOT + cover.medallion;
    img.alt = '';
    if (cover.focus) img.style.objectPosition = cover.focus;
    chip.appendChild(img);
    return chip;
  }
  return el('div', 'day-hero-saint day-hero-saint--icon', ICON_SAINT);
}

// The full-width band at the top of the page. With a cover it is the day's
// mosaic image under the shared hero scrims; without one it is the quiet
// fallback vignette. Either way the nav, heading, feast titles and fast
// chip sit on it in the ink-image family, so text stays legible in both
// themes.
function buildHero({ valid, isToday, dateStr, todayStr, day, cover }) {
  const hero = el('header', 'day-hero');

  if (cover && cover.image) {
    const img = el('img', 'day-hero-img');
    img.src = ROOT + cover.image;
    img.alt = '';
    if (cover.focus) img.style.objectPosition = cover.focus;
    hero.appendChild(img);
    hero.appendChild(el('div', 'day-hero-scrim'));
  } else {
    hero.classList.add('day-hero--fallback');
  }

  const inner = el('div', 'day-hero-inner');

  const nav = el('div', 'day-nav');
  const prev = el('a', 'day-nav-arrow', CHEVRON_LEFT);
  prev.href = `#/day/${valid ? shiftDate(dateStr, -1) : todayStr}`;
  prev.setAttribute('aria-label', 'Previous day');
  nav.appendChild(prev);
  nav.appendChild(text('p', 'eyebrow', isToday ? 'Today' : 'Daily Readings'));
  const next = el('a', 'day-nav-arrow', CHEVRON_RIGHT);
  next.href = `#/day/${valid ? shiftDate(dateStr, 1) : todayStr}`;
  next.setAttribute('aria-label', 'Next day');
  nav.appendChild(next);
  if (!isToday) {
    const todayLink = text('a', 'day-today-link', 'Today');
    todayLink.href = '#/day/today';
    nav.appendChild(todayLink);
  }
  inner.appendChild(nav);

  const head = el('div', 'day-hero-head');
  head.appendChild(text('h1', 'day-title', valid ? formatDateHeading(dateStr) : 'Daily Readings'));

  const titles = day && day.titles ? day.titles : [];
  titles.forEach((t) => head.appendChild(text('p', 'day-feast-title', t)));

  if (day && day.fast) {
    const chip = el('p', 'day-fast', ICON_FISH);
    chip.appendChild(text('span', null, day.fast));
    head.appendChild(chip);
  }

  const row = el('div', 'day-hero-row');
  if (valid) row.appendChild(buildSaintChip(cover));
  row.appendChild(head);
  inner.appendChild(row);

  hero.appendChild(inner);
  return hero;
}

// The first body group: who the day commemorates, and where to read more
// about them. A quiet serif-italic line, then an inline "Read the Lives"
// link into the library's synaxarion item (or the graceful note when that
// life is not yet translated) — no card. When the day has a cover, its
// round medallion stands to the left of the line in a flex row; without
// one the line stands alone, exactly as before.
function buildCommemoration(day, synaxarionItem, cover) {
  const group = el('div', 'day-group');

  if (day && day.saints && day.saints.length) {
    const saints = text('p', 'day-saints', `Commemorated: ${day.saints.join('; ')}.`);
    if (cover && cover.medallion) {
      const row = el('div', 'day-commem');
      const img = el('img', 'day-commem-img');
      img.src = ROOT + cover.medallion;
      img.alt = '';
      if (cover.focus) img.style.objectPosition = cover.focus;
      row.appendChild(img);
      row.appendChild(saints);
      group.appendChild(row);
    } else {
      group.appendChild(saints);
    }
  }

  if (synaxarionItem) {
    const a = el('a', 'link-arrow day-lives-link');
    a.href = `#/item/${synaxarionItem.id}`;
    a.appendChild(document.createTextNode(`Read the Lives: ${synaxarionItem.title} `));
    a.insertAdjacentHTML('beforeend', ICON_CHEVRON_RIGHT);
    group.appendChild(a);
  } else {
    group.appendChild(
      emptyNote(ICON_SAINT, 'The Lives for this day are not yet translated in this library.')
    );
  }
  return group;
}

// A reading is SECONDARY when its label begins with "Vespers" or "Matins"
// — the Old-Testament / eve-of-feast lections appointed only on major
// feasts. Everything else (Epistle, Gospel, feast-specific pericopes) is
// primary and belongs to "At the Liturgy".
function isSecondaryReading(reading) {
  return /^(Vespers|Matins)/.test(String(reading.label || ''));
}

// The icon image for a reading, or null when none can be resolved — null
// means "render exactly as before, text only", so ordinary days with no
// mapping show no empty frame. Priority:
//   a) a feast GOSPEL reading — a Gospel whose label carries a parenthetical
//      qualifier like "Gospel (Transfiguration)" — takes the day's own cover
//      medallion: the Gospel narrates the feast event itself. Epistles and
//      OT lections keep their author's icon even on feasts (Peter beside
//      2 Peter, Moses beside Exodus), so a feast day reads as a row of its
//      witnesses, not the same image repeated down the page;
//   b) an NT reading whose book code is in the icons map (the evangelists
//      and apostles);
//   c) an OT reading (no book code) whose leading book name in the ref
//      string ("3 [1] Kings 19:3" -> "Kings") is in the map's ot_books.
function resolveReadingIcon(reading, icons, cover) {
  const isFeastLabelled = /\([^)]*\)/.test(String(reading.label || ''));
  if (isFeastLabelled && GOSPEL_BOOKS.includes(reading.book) && cover && cover.medallion) {
    return cover.medallion;
  }
  const books = icons.books || {};
  if (reading.book && books[reading.book]) return books[reading.book];
  if (!reading.book) {
    const otBooks = icons.ot_books || {};
    const m = /^[\d\s[\]]*([A-Za-z]+)/.exec(String(reading.ref || ''));
    if (m && otBooks[m[1]]) return otBooks[m[1]];
  }
  return null;
}

// ref string (dash-normalized, matching build_reading_texts.py's own
// normalization) -> verses[], for the day's reading-texts file, or an empty
// map when there is none / it fetched nothing.
function readingTextsByRef(readingTexts) {
  const byRef = new Map();
  if (readingTexts && Array.isArray(readingTexts.readings)) {
    readingTexts.readings.forEach((r) => {
      if (r && r.ref) byRef.set(r.ref, r.verses || []);
    });
  }
  return byRef;
}

// The collapsed "Read the passage" disclosure under a primary reading —
// native <details>/<summary>, no new JS state. English-only, plain text via
// textContent (never innerHTML of fetched content); one <p> per verse line.
function buildPassageDisclosure(verses) {
  const details = el('details', 'day-passage');
  const summary = el('summary', 'day-passage-summary', ICON_SCROLL);
  summary.appendChild(text('span', null, 'Read the passage'));
  details.appendChild(summary);
  const body2 = el('div', 'day-passage-body');
  verses.forEach((v) => body2.appendChild(text('p', 'day-passage-verse', v)));
  details.appendChild(body2);
  return details;
}

// "At the Liturgy" — the primary readings, the dominant element of the
// page. Each entry is a typographic block: a small uppercase run-in label,
// the reference large and serif (the visual anchor, echoing the hero's
// feast title), and the Chrysostom homily note underneath. When an icon
// resolves for the reading it stands to the left as an arched plate and
// the text wraps in its own column; without one the entry is text only,
// exactly as before. Entries are separated by hair rules, not cards. When
// the day's reading-texts file has this reading's passage, a collapsed
// "Read the passage" disclosure sits under the homily note.
function buildPrimaryReadings(day, map, itemsBySourceRef, itemsByHomilyKey, cover, icons, readingTexts) {
  const group = el('div', 'day-group');
  group.appendChild(text('p', 'eyebrow', 'At the Liturgy'));

  const readings = day && day.readings ? day.readings.filter((r) => !isSecondaryReading(r)) : [];
  if (!readings.length) {
    group.appendChild(
      emptyNote(ICON_BOOK_CROSS, 'The readings for this date are not yet available in this library.')
    );
    return group;
  }

  const textsByRef = readingTextsByRef(readingTexts);
  const list = el('ul', 'day-liturgy');
  readings.forEach((reading) => {
    const li = el('li', 'day-liturgy-item');
    const iconSrc = resolveReadingIcon(reading, icons, cover);
    if (iconSrc) {
      li.classList.add('day-liturgy-item--with-icon');
      const img = el('img', 'day-liturgy-icon');
      img.src = ROOT + iconSrc;
      img.alt = '';
      li.appendChild(img);
    }
    const body2 = iconSrc ? el('div', 'day-liturgy-text') : li;
    body2.appendChild(text('span', 'day-liturgy-label', reading.label));
    body2.appendChild(text('span', 'day-liturgy-ref', reading.ref));
    const homilyNote = buildHomilyNote(reading, map, itemsBySourceRef, itemsByHomilyKey);
    if (homilyNote) body2.appendChild(homilyNote);
    const verses = textsByRef.get(reading.ref);
    if (verses && verses.length) body2.appendChild(buildPassageDisclosure(verses));
    if (iconSrc) li.appendChild(body2);
    list.appendChild(li);
  });
  group.appendChild(list);
  return group;
}

// "Also Appointed" — the secondary Vespers/Matins lections, much quieter
// than the primary readings: a plain uppercase label (no accent) and one
// compact flex row per reading — a small arched thumb when an icon
// resolves, then the fixed-width kind and the serif ref. No homily note
// (they carry no book code, so buildHomilyNote would return null anyway).
// Absent entirely on ordinary days — the group is only rendered when at
// least one exists.
function buildSecondaryReadings(day, cover, icons) {
  const readings = day && day.readings ? day.readings.filter(isSecondaryReading) : [];
  if (!readings.length) return null;

  const group = el('div', 'day-group');
  group.appendChild(text('p', 'day-also-label', 'Also Appointed'));

  const list = el('ul', 'day-also');
  readings.forEach((reading) => {
    const li = el('li', 'day-also-item');
    const iconSrc = resolveReadingIcon(reading, icons, cover);
    if (iconSrc) {
      const img = el('img', 'day-also-icon');
      img.src = ROOT + iconSrc;
      img.alt = '';
      li.appendChild(img);
    }
    li.appendChild(text('span', 'day-also-kind', reading.label));
    li.appendChild(text('span', 'day-also-ref', reading.ref));
    list.appendChild(li);
  });
  group.appendChild(list);
  return group;
}

export async function renderDay(param) {
  const view = document.getElementById('view-day');
  const todayStr = localDateStr(new Date());
  const isToday = param === 'today';
  const dateStr = isToday ? todayStr : param;
  const valid = /^\d{4}-\d{2}-\d{2}$/.test(dateStr) && !Number.isNaN(new Date(dateStr).getTime());

  view.innerHTML = '';

  if (!valid) {
    view.appendChild(buildHero({ valid, isToday, dateStr, todayStr, day: null, cover: null }));
    const body = el('div', 'day-body');
    body.appendChild(emptyNote(ICON_BOOK_CROSS, 'That date is not one this page understands.'));
    view.appendChild(body);
    return;
  }

  const [indexData, map, covers, readingIcons, day, readingTexts] = await Promise.all([
    loadIndex(),
    loadChrysostomMap(),
    loadCovers(),
    loadReadingIcons(),
    loadDay(dateStr),
    loadReadingText(dateStr),
  ]);

  const itemsBySourceRef = new Map();
  // Fallback when source_ref is absent (homily-57-matthew, homily-9-1cor,
  // homily-13-1cor carry none): their ids encode the homily — homily-<n>-<book>
  // or chrysostom-<n> (the latter is Matthew's series).
  const ID_BOOK = { matthew: 'Matt', mark: 'Mark', luke: 'Luke', john: 'John', acts: 'Acts', romans: 'Rom', '1cor': '1Cor', '2cor': '2Cor', gal: 'Gal', eph: 'Eph', phil: 'Php', col: 'Col', heb: 'Heb' };
  const itemsByHomilyKey = new Map();
  (indexData.items || []).forEach((item) => {
    if (item.source_ref) itemsBySourceRef.set(item.source_ref, item);
    let m2;
    if ((m2 = /^homily-(\d+)-([a-z0-9]+)$/.exec(item.id)) && ID_BOOK[m2[2]]) {
      itemsByHomilyKey.set(`${ID_BOOK[m2[2]]}:${Number(m2[1])}`, item);
    } else if ((m2 = /^chrysostom-(\d+)$/.exec(item.id))) {
      itemsByHomilyKey.set(`Matt:${Number(m2[1])}`, item);
    }
  });
  const synaxarionItem = (indexData.items || []).find((i) => i.id === `synaxarion-${dateStr}`) || null;
  const cover = synaxarionItem && synaxarionItem.cover_key ? covers[synaxarionItem.cover_key] || null : null;

  view.appendChild(buildHero({ valid, isToday, dateStr, todayStr, day, cover }));

  const body = el('div', 'day-body');
  body.appendChild(buildCommemoration(day, synaxarionItem, cover));
  body.appendChild(buildPrimaryReadings(day, map, itemsBySourceRef, itemsByHomilyKey, cover, readingIcons, readingTexts));
  const secondary = buildSecondaryReadings(day, cover, readingIcons);
  if (secondary) body.appendChild(secondary);
  view.appendChild(body);
}
